name: Generate Pacman

on:
  schedule:
    - cron: "30 0 * * *"   # tiap hari jam 00:30 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate pacman animation
        uses: abozanona/pacman-contribution-graph@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?color_dots=#ffee00,#ffaa00,#ff7700,#ff5500&color_pacman=#ffff00

      - name: Push to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
